version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgrespass
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "1323:1323"
  #   volumes:
  #     - ./:/go/src/app/
  #   environment:
  #     - PG_HOST=postgres
  #     - PG_PORT=5432
  #     - PG_USER=postgres
  #     - PG_PASSWORD=postgrespass
  #     - PG_DB_NAME=postgres
volumes:
  pg-data: 